BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[REQ_DOCUMENT] (
    [REQ_DOCUMENT_ID] INT NOT NULL,
    [DOCUMENT_CODE] NVARCHAR(1000) NOT NULL,
    [DOCUMENT_NAME_TH] NVARCHAR(1000) NOT NULL,
    [REQUEST_TYPE] NVARCHAR(1000) NOT NULL,
    [RECORD_STATUS] NVARCHAR(1000) NOT NULL,
    CONSTRAINT [REQ_DOCUMENT_pkey] PRIMARY KEY CLUSTERED ([REQ_DOCUMENT_ID])
);

-- CreateTable
CREATE TABLE [dbo].[VW_REQ_STUDENT_REPORT] (
    [REQ_YDC_ID] NCHAR(15) NOT NULL,
    [REQUEST_YEAR] INT,
    [REQUEST_MONTH] INT,
    [REQ_DOCUMENT_ID] INT,
    [DOCUMENT_CODE] NCHAR(10),
    [DOCUMENT_NAME_TH] NVARCHAR(255),
    [TOTAL_REQUESTS] INT,
    [E_SERVICE] INT,
    [WORK_IN] INT,
    CONSTRAINT [VW_REQ_STUDENT_REPORT_pkey] PRIMARY KEY CLUSTERED ([REQ_YDC_ID])
);

-- CreateTable
CREATE TABLE [dbo].[VW_REQ_TEACHER_REPORT] (
    [REQ_YDC_ID] NCHAR(15) NOT NULL,
    [REQUEST_YEAR] INT,
    [REQUEST_MONTH] INT,
    [REQ_DOCUMENT_ID] INT,
    [DOCUMENT_CODE] NCHAR(10),
    [DOCUMENT_NAME_TH] NVARCHAR(255),
    [TOTAL_REQUESTS] INT,
    [E_SERVICE] INT,
    [WORK_IN] INT,
    CONSTRAINT [VW_REQ_TEACHER_REPORT_pkey] PRIMARY KEY CLUSTERED ([REQ_YDC_ID])
);

-- CreateTable
CREATE TABLE [dbo].[REQ_GROUP_REPORT] (
    [id] INT NOT NULL IDENTITY(1,1),
    [Note] NVARCHAR(255) NOT NULL,
    [createdAt] DATETIME2 CONSTRAINT [REQ_GROUP_REPORT_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [REQ_GROUP_REPORT_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- CreateTable
CREATE TABLE [dbo].[REQ_MORE_REPORT] (
    [id] INT NOT NULL IDENTITY(1,1),
    [REQ_YDC_ID] NCHAR(20) NOT NULL,
    [REQUEST_YEAR] INT NOT NULL,
    [REQUEST_MONTH] INT NOT NULL,
    [REQ_DOCUMENT_ID] INT NOT NULL,
    [DOCUMENT_CODE] NCHAR(10) NOT NULL,
    [DOCUMENT_NAME_TH] NVARCHAR(255) NOT NULL,
    [TOTAL_REQUESTS] INT NOT NULL,
    [E_SERVICE] INT NOT NULL,
    [WORK_IN] INT NOT NULL,
    [GROUP_ID] INT NOT NULL,
    CONSTRAINT [REQ_MORE_REPORT_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- AddForeignKey
ALTER TABLE [dbo].[REQ_MORE_REPORT] ADD CONSTRAINT [REQ_MORE_REPORT_GROUP_ID_fkey] FOREIGN KEY ([GROUP_ID]) REFERENCES [dbo].[REQ_GROUP_REPORT]([id]) ON DELETE NO ACTION ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
